### PR TITLE
Fixes Metric name export option

### LINKED ISSUE #527: Export results to JSON on metric docs (by metric name) doesn't work
Submitted by user: I'm on the page: https://coronavirus.data.gov.uk/metrics/name

And I was hoping to use the "Export results to JSON" link to get a list of all metrics. 

But this link doesn't seem to work when I click it. 

I've tried a couple of browsers (Firefox and Edge) and getting the same result from both. I tried adding some filters/without filters but getting the same result.
metricsbug

### PR DESCRIPTION
**Pull request by beawitcht**
resolves #527

### CODE REVIEW

File: src/pages/MetricDocs/Sections/MetricName.js [hunk 1]
```diff
@@ -146,7 +146,7 @@ const Metrics: ComponentType<*> = ({ metrics, setUri }) => {
         </div>
         <RenderMetrics data={ data }
                        filterFunc={ () => true }
-                       download={ URLs["genericApiMetricSearch"] + `?search=${userInput}` }
+                       download={ URLs["genericApiMetricSearch"] + `?search=${userInput}` + `&category=${category}` + `&tags=${types.join(",")}` }
```
Comment (xenatisch) [inline src/pages/MetricDocs/Sections/MetricName.js]: We need to use `utils.createQuery` to generate this one. This means that we should predefine the parameters array (possibly in a `useEffect`) and ensure that empty params are excluded.

**Review by xenatisch — CHANGES_REQUESTED** [review]
Just needs a minor change in the implementation of query params.

**Review by xenatisch — APPROVED** [review]
